export default function Head({ params }) {
    return (
        <>
            <title>Dotazníky Výzkumu Odolnosti</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script
                src="https://www.google.com/recaptcha/api.js?&render=explicit"
                async
                defer
            ></script>
        </>
    )
}
